config/routes.rb
Rails.application.routes.draw do

  resources :tournaments
  resources :timertests
  resources :users, only: [:show]
  resources :competitors, only: [:index, :show]
  resources :favorites, only: [:create, :destroy]
  resources :subscriptions, only: [:create]
  resources :games, only: [:show]

  get 'calendar', :to => 'tournaments#index_calendar'

  root 'tournaments#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/user.rb
class User < ActiveRecord::Base
  #Can favorite models that are favorable
  has_many :favorites, inverse_of: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]

	def self.from_omniauth(access_token, signed_in_resource = nil)
	    data = access_token.info
	    user = User.where(:email => data["email"]).first

      if user
        user.provider = access_token.provider
        user.uid = access_token.uid
        user.token = access_token.credentials.token
        user.image = access_token.info.image
        user.save
	    else
	      user = User.create(
          name:     data["name"],
       	  email:    data["email"],
      	  password: Devise.friendly_token[0,20],
          uid:      access_token.uid,
          provider: access_token.provider,
          token:    access_token.credentials.token,
          image:    data["image"]
	      )
	    end
	    user
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

      if @user
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(user_params[:id])

    favorite_tournaments = @user.favorites.where(favoritable_type: "Tournament")
    @favorite_tournaments = favorite_tournaments.map {|t| Tournament.find(t.favoritable_id)}.sort_by {|t| t.title.downcase}

    favorite_competitors = @user.favorites.where(favoritable_type: "Competitor")
    @favorite_competitors = favorite_competitors.map {|c| Competitor.find(c.favoritable_id)}.sort_by {|c| c.name.downcase}
  end

  private

  def user_params
    params.permit(:id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% title @user.name %>

<div class="row pad-top-sm">

  <div class="hidden-sm hidden-xs col-md-2">
    <div class="row portfolio-item thumbnail infoplus" style="height:165px;width:165px">
      <img style="" src=<%= @user.image %><br>
    </div>
  </div>

  <div class="col-md-10">
    <div class="row portfolio-item infoplus" style="height:165px">
      <span class="h2"><%= @user.name %></span><br><hr>
      <p>Signed in as <a target="_blank" href="http://www.gmail.com"><%= @user.email %></a><br>Check <a target="_blank" href="https://calendar.google.com/">your calendar</a></p>
    </div>
  </div>

</div>


<div class="row pad-top">
  <div class="col-md-6">
    <div class="row portfolio-item thumbnail infoplus">
      <span class="h3">Favorite Tournaments</span>
      <% if @favorite_tournaments %> <br><hr>
      <% @favorite_tournaments.each do |favorite_tournament| %>
      <%= link_to favorite_tournament.title, tournament_path(favorite_tournament) %>
      <% unless favorite_tournament == @favorite_tournaments.last %>
      <b> / </b>
      <% end %>
      <% end %>
      <% else %>
      <p> No favorites yet </p>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="row portfolio-item thumbnail infoplus">
      <span class="h3">Favorite Competitors</span><br><hr>
    <% if @favorite_competitors %>
      <% @favorite_competitors.each do |favorite_competitor| %>
       <span class="p"><%= link_to favorite_competitor.name, competitor_path(favorite_competitor) %></span>
       <% unless favorite_competitor == @favorite_competitors.last %>
       <b>/</b>
       <% end %>
      <% end %>
    <% else %>
      <p> No favorites yet </p>
    <% end %>
    </div>
    </div>
  </div>
</div>