config/routes.rb
Rails.application.routes.draw do

  resources :tournaments
  resources :timertests
  resources :users, only: [:show]
  resources :competitors, only: [:index, :show]
  resources :favorites, only: [:create, :destroy]
  resources :subscriptions, only: [:create]
  resources :games, only: [:show]

  get 'calendar', :to => 'tournaments#index_calendar'

  root 'tournaments#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  # Can be favorited
  has_many :favorites, as: :favoritable
  has_many :streams
  has_and_belongs_to_many :competitors
  belongs_to :game

  def self.by_year(year: DateTime.now.year)
    where(
      start_time: year_start_date(year)..year_end_date(year),
      end_time:   year_start_date(year)..year_end_date(year)
      ).order(start_time: :desc)
  end

  # expects month as integer
  def self.by_month(month: DateTime.now.month, year: DateTime.now.year)
    where(
      start_time: month_start_date(month, year)..month_end_date(month, year),
      end_time:   month_start_date(month, year)..month_end_date(month, year)
      ).order(start_time: :desc)
  end

  def self.by_week(week: current_week_number, year: DateTime.now.year)
    where(
      start_time: week_start_date(week, year)..week_end_date(week, year),
      end_time:   week_start_date(week, year)..week_end_date(week, year)
      ).order(start_time: :desc)
  end

  def self.by_day(date: DateTime.now)
    self.order(start_time: :desc).select {|tournament| tournament.is_live?(date: date)}
  end

  def is_live?(date: DateTime.now)
    self.start_time <= date && self.end_time >= date
  end

  def is_over?
    self.end_time <= DateTime.now
  end

  private

  def self.year_start_date(year)
    Time.utc(year)
  end

  def self.year_end_date(year)
    year_start_date(year).end_of_year
  end

  def self.month_start_date(month, year)
    year_start_date(year) + (month - 1).months
  end

  def self.month_end_date(month, year)
    month_start_date(month, year).end_of_month
  end

  def self.week_start_date(week, year)
    (year_start_date(year) + (week - 1).weeks).beginning_of_week
  end

  def self.week_end_date(week, year)
    week_start_date(week, year).end_of_week
  end

  def self.current_week_number
    DateTime.now.strftime("%U").to_i
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @games = Game.order(:title)
    cookies[:welcomed] = {:value => true, :expires => Time.now + 6.months}

    if params[:sort_option] == "search"
      @tournaments = Search.new(params[:search]).matches
    elsif params[:sort_option] == "game"
      @tournaments = Tournament.where(game_id: params[:game_id]).order(start_time: :desc)
      @title = Game.find(params[:game_id]).title
    elsif params[:sort_option].in? ["year", "month", "week", "day"]
      @tournaments = Tournament.send("by_" + params[:sort_option])
    else
      @tournaments = Tournament.order(start_time: :desc)
      @title = ""
    end

    @title ||= params[:sort_option].capitalize

    @tournaments = @tournaments.partition {|tournament| tournament.is_live?}.flatten
    @tournaments = @tournaments.paginate(page: params[:page], per_page: 12)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index_calendar
    @games = Game.all
    @tournaments = Tournament.order(created_at: :desc)
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  private

  def tournament_params
    params.require(:tournament).permit(:name, :start_time, :end_time, :game_id, :image, :page)
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_tournament.html.erb
<div id="my-tournaments">
  <% if tournament.is_live? %>
  <div class="col-md-12 col-sm-12 col-xs-12 portfolio-item">
    <% if tournament.image_default %>
      <a href="/tournaments/<%=tournament.id%>" class="thumbnail">
        <img class="hidden-xs grayscale" id="<%= tournament.id %>" src="<%= tournament.image_large %>">
        <img class="hidden-lg hidden-sm hidden-md grayscale" id="<%= tournament.id %>" style="width:100%" src="<%= tournament.image_default %>">
      </a>
    <% else %>
      <a href="/tournaments/<%=tournament.id%>" class="thumbnail">
        <img class="grayscale" style="max-height:200px; width:100%" id="<%= tournament.id%>" src="http://www.download-free-wallpaper.com/img50/svwyzdhmpisjaqkbykpz.png">
      </a>
    <% end %>
    <div class="info" id="<%= tournament.id %>">
      <div id="<%= tournament.id %>">
        <span class="h4">
          <a href="/tournaments/<%= tournament.id %>"><span class="label label-warning">Live</span></a>
          <%= tournament.title%></span><br>
        <span id="<%= tournament.id %>-default-index-text" class="">
          <p class="pad-top-xs">
            <b><%= tournament.city %></b>–<%= tournament.start_time.strftime('%a %d %b %Y') %></p>
        </span>
        <span id="<%= tournament.id %>-hover-index-text" style="display:none">
          <p class="pad-top-xs"><%= raw(tournament.description[0..180] + "...") %></p>
        </span>
      </div>
    </div>
  </div>

  <% else %>

    <div class="col-md-4 col-sm-6 col-lg-3 col-xs-12 portfolio-item">
      <% if tournament.image_default %>
        <a href="/tournaments/<%=tournament.id%>" class="thumbnail">
          <img class="grayscale" id="<%= tournament.id%>" src="<%= tournament.image_default %>">
        </a>
      <% else %>
        <a href="/tournaments/<%=tournament.id%>" class="thumbnail">
          <img class="grayscale" style="max-height:200px; width:100%" id="<%= tournament.id%>" src="http://www.download-free-wallpaper.com/img50/svwyzdhmpisjaqkbykpz.png">
        </a>
      <% end %>
      <div class="info" id="<%= tournament.id %>">
        <div id="<%= tournament.id %>">
          <span class="h4"><%= tournament.short_title%></span><br>
          <span id="<%= tournament.id %>-default-index-text" class="">
            <b><%= tournament.city %></b>
            –
            <%= tournament.start_time.strftime('%a %d %b %Y') %>
          </span>
          <span id="<%= tournament.id %>-hover-index-text" style="display:none">
            <p><%= raw(tournament.description[0..40]) %></p>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tournaments/index.html.erb
<% if display_welcome? %>
<div class="container hidden-sm hidden-xs" >
  <div class="alert alert-default alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p class="h1 light-text intro text-center">Welcome to <i class="logo-detail">ESPORTAL</i>&nbsp;!</p>
    <br><br>
    <span class='visible'>
      <ul>
        <li style="font-size:24px" class="light-text text-center">Making tracking and following of esports tournaments easier</li>
        <li style="font-size:24px" class="light-text text-center">Keep track of your favorite players and teams</li>
        <li style="font-size:24px" class="light-text text-center">Get a notification when an event is about to start</li>
      </ul>
    </span>
  </div>
</div>
<% end %>

<% title @title %>
<div class="row pad-bot-lg">
  <div class="col-md-6 col-lg-6 col-xs-12 hidden-xs col-sm-6">
    <div class="input-group" style="padding-top:2px">
      <div class="input-append">
        <%= form_tag(tournaments_path, :method => "get", class: "navbar-form", id: "search-form") do %>
        <%= hidden_field_tag :sort_option, :search %>
        <%= text_field_tag :search, params[:search], class: "form-control btn-border", placeholder: "Search Items" %>

          <button class="btn btn-warning btn-border" type="submit">&nbsp;search&nbsp;</button>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-lg-6 col-sm-6">
    <div class="btn pull-right">
      <div class="btn-group">
        <button type="button" class="btn btn-warning btn-border dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if params[:game_id] %>
            <%= @games.find{|game| game.id == params[:game_id].to_i}.title %>
          <% else %>
            Games
          <% end %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <% if params[:game_id] %>
            <li><%= link_to "All Games", tournaments_path %></li>
            <hr>
          <% end %>
          <% @games.each do |game| %>
            <li><%= link_to game.title, tournaments_path(sort_option: "game", game_id: game.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="btn-group btn pull-right" role="group" aria-label="...">
      <%= link_to "Year", tournaments_path(sort_option: "year"), class: "btn btn-border btn-warning" %>
      <%= link_to "Month", tournaments_path(sort_option: "month"), class: "btn btn-border btn-warning" %>
      <%= link_to "Week", tournaments_path(sort_option: "week"), class: "btn btn-border btn-warning" %>
      <%= link_to "Day", tournaments_path(sort_option: "day"), class: "btn btn-border btn-warning" %>
    </div>
  </div>
</div>
</div>

<div class="container special">

  <div id="my-tournaments">
    <%= render @tournaments %>
  </div>

  <div id="infinite-scrolling">
    <%= will_paginate %>
  </div>

</div>

app/views/tournaments/index.js.erb
$('#my-tournaments').append('<%= j render @tournaments %>');
<% if @tournaments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @tournaments %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/tournaments/index_calendar.html.erb
<% title "Calendar" %>

<div class="row" style="padding-bottom:15px">
    <div id="events_calendar">
      <%= render partial: "/events/calendar", locals: {events: @tournaments} %>
    </div>
</div>

app/views/tournaments/show.html.erb
<% t = @tournament.start_time.to_s  %>
<% t.gsub!(" UTC", "") %>
<% parsable = t.gsub!(" ", "T") %>
<script>var deadline = "<%= parsable %>"</script>

<% title @tournament.short_title %>

<div class="row pad-bot-sm">
  <div class="col-md-12 col-sm-12">
    <div class="row">
      <div class="col-md-12 col-sm-12 h1"><%= get_game_title(@tournament.game_id) %>: <span class="light-text"><%= @tournament.short_title %>
          <% if @tournament.is_live? %>
            <span class="h3 light-text red">(LIVE)</span>
          <% elsif @tournament.is_over? && @tournament.end_time > @tournament.start_time %>
            <span class="h3 light-text red">(OVER)</span>
          <% else %>
            <span id="clockdiv">
            <span class="h3 light-text red">Starts in </span><span class="days red h3 light-text text-right"></span> <span class="light-text red h3 hours"></span><span class="light-text red h3 minutes"></span><span class="light-text h3 red seconds"></span>
          <% end %>
        </span>
       </div>
      </div>
    </div>
  </div>

<div class="row">
  <div class="col-md-12">
    <div class="portfolio-item thumbnail">

      <% if @tournament.image_default %>
        <img class="hidden-xs" src="<%= @tournament.image_large %>">
        <img class="hidden-lg hidden-sm hidden-md" src="<%= @tournament.image_default %>">
      <% else %>
        <img class="grayscale base-prop" src="http://goo.gl/7ezbJB">
      <% end %>

      <% if user_signed_in? %>
        <% favorite_params = {favorite: {user_id: current_user.id, favoritable_id: @tournament.id, favoritable_type: "Tournament"}} %>

        <% if current_user.favorites.where(favoritable_id: @tournament.id).any? %>
          <%= button_to favorite_path(favorite_params), method: "delete", class: "buttonz btn btn-border white btn-default", 'aria-label' => "Left Align", disabled: !user_signed_in? do %>
          <i class="fa fa-heart"></i> Unfollow
          <% end %>
        <% else %>
          <%= button_to favorites_path(favorite_params), action: "create", class: "buttonz btn btn-border white btn-default", 'aria-label' => "Left Align", disabled: !user_signed_in? do %>
          <i class="fa fa-heart"></i> Follow
          <% end %>
        <% end %>

        <%= button_to subscriptions_path(favorite_params),id: 'sub_text', action: "create", class: "calendar-submit buttony btn btn-border white btn-default", 'aria-label' => "Left Align", disabled: !user_signed_in? do %>
          <i class="fa fa-calendar-plus-o"></i> Subscribe
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row infoplus">
  <div class="col-md-6 col-sm-12 col-xs-12 col-lg-6">
    <div class="hidden-sm hidden-xs" style="border-right:1px solid black"></div>
      <section class="pad-bot-sm">
        <span class="h2 light-text"><%= @tournament.title %></span>
      </section>
      <section>
        <p>  <b>Location: <%= @tournament.city %></b> – <%= @tournament.description.gsub(/(&nbsp;)/, ' ') %></p>
      </section>
  </div>

  <div class="col-md-6 col-sm-12 col-xs-12 col-lg-6">
    <% if @tournament.streams.any? %>
      <% @tournament.streams.each do |stream| %>
      <section class="pad-bot-sm">
        <span class="h2"><%= link_to stream.url do %><i class="fa fa-globe"></i> Stream</i><% end %>
          <span class="light-text pull-right"><%= @tournament.favorites.count %> followers</span>
        </span>
      </section>
      <% end %>
    <% else %>
      <section>
        <p>Stream list soon</p>
      </section>
    <% end %>
    <p class="mon"><b>Starts on <%= Date::MONTHNAMES[@tournament.start_time.mon] %><i class="day date"> <%= @tournament.start_time.day %></b></i>. Competitors to follow :</p><br><br>

    <section>
      <% @tournament.competitors.order(:name).each do |competitor| %>
        <% if user_signed_in? %>
          <% favorite_params = {favorite: {user_id: current_user.id, favoritable_id: competitor.id, favoritable_type: "Competitor"}} %>
        <% end %>
        <%= button_to competitor.name, favorites_path(favorite_params), action: "create", class: "btn-competitor btn btn-xs btn-default", disabled: !user_signed_in? %>
      <% end %>
    </section>
  </div>
</div>